### ISSUE TITLE
gloo-timers 0.2.3 can panic

### ISSUE THREAD

**Issue by ctm** [rustwasm/gloo#187]
### Describe the Bug

Code using gloo-timers 0.2.3 can panic when the timer is dropped.

### Steps to Reproduce

1. Go to https://github.com/ctm/gloo-timers-regression
2. clone the repository
3. yarn install && yarn dev:start
4. open http://localhost:8080
5. look at JavaScript console

If applicable, add a link to a test case (as a zip file or link to a repository
we can clone).

### Expected Behavior

There should be no panic.

### Actual Behavior

There is a panic.

<img width="1418" alt="Screen Shot 2022-01-28 at 09 49 09" src="https://user-images.githubusercontent.com/26245/151587957-0bfdefe7-aaed-4bee-b825-03f861ec9f39.png">

**Comment by hamza1311** [comment]
I can't reproduce this behavior locally. 
```toml
# Cargo.toml 
[package]
name = "gloo-timers-regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = "0.2.3"
gloo-console = "*"
```

```rust
// src/main.rs 
#[macro_use]
extern crate gloo_console;

use gloo_timers::callback::Timeout;
use wasm_bindgen::prelude::*;

const DELAY_MILLIS: u32 = 30; // 30 seconds

fn main() {
    log!("hello");
    let tt = Timeout::new(DELAY_MILLIS, move || { log!("inside") });
    drop(tt);
}
```

I used `trunk serve` with a simple `index.html` file, loaded it in browser and found that "hello" is logged but not "inside", showcasing that drop worked.
